#!/usr/bin/env bash

USAGE="<commit>"
LONG_USAGE=""

source "$(git --exec-path)/git-sh-setup"

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

function main() {

    COMMIT=$1

    if [[ $COMMIT =~ HEAD.* ]] || [[ $COMMIT =~ [0-9a-f]{5,40} ]]; then
        git rebase --interactive --autosquash $COMMIT
    else
        git rebase --interactive --autosquash HEAD~$1
    fi

}

main $@
