#!/usr/bin/env bash

USAGE="<base>"
LONG_USAGE=""

source "$(git --exec-path)/git-sh-setup"
source "utils/setup-configuration-files.sh"

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

function main() {

    BASE=$1

    base_branch=''

    if [[ -n $BASE ]]; then
        base_branch=$BASE
    else
        base_branch=$DEVELOPMENT_BRANCH
    fi

    git fetch origin $base_branch:$base_branch
    git rebase $base_branch

}

main $@
