#!/usr/bin/env bash

USAGE="<commit>"
LONG_USAGE=""

source "$(git --exec-path)/git-sh-setup"

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $MAIN_BRANCH ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES, MAIN_BRANCH and DEVELOPMENT_BRANCH.'
    fi
}

function main() {

    COMMIT=$1

    base_commit=''

    if [[ -n $COMMIT ]]; then
        base_commit=$COMMIT
    else
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        first_branch_commit=$(diff --old-line-format='' --new-line-format='' <(git rev-list --first-parent "${1:-$DEVELOPMENT_BRANCH}") <(git rev-list --first-parent "${2:-HEAD}") | head -1)
        base_commit=$first_branch_commit
    fi

    git rebase --interactive --autosquash $base_commit

}

setup_configuration
main $@
