#!/usr/bin/env bash

USAGE="<base>"
LONG_USAGE=""

source "$(git --exec-path)/git-sh-setup"

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $MAIN_BRANCH ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES, MAIN_BRANCH and DEVELOPMENT_BRANCH.'
    fi
}

function main() {

    BASE=$1

    base_branch=''

    if [[ -n $BASE ]]; then
        base_branch=$BASE
    else
        base_branch=$DEVELOPMENT_BRANCH
    fi

    git fetch origin $base_branch:$base_branch
    git rebase $base_branch

}

setup_configuration
main $@
