#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Removes current branch locally and from origin. It will not apply to branches listed in PROTECTED_BRANCHES."

source "$(git --exec-path)/git-sh-setup"

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES and DEVELOPMENT_BRANCH.'
    fi
}

function main() {

    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ $PROTECTED_BRANCHES =~ $current_branch ]]; then
        die "$current_branch branch is protected and will not be removed."
    fi

    git checkout $DEVELOPMENT_BRANCH
    git branch -D $branch_to_remove
    git push origin :$branch_to_remove

}

setup_configuration
main
