#!/bin/sh

source "$(git --exec-path)/git-sh-setup"

usage() {
    echo "usage: git squash <commit>"
}

function main() {

    if [[ $# -ne 1 ]]; then
        usage
        exit 1
    fi

    COMMIT=$1

    if [[ $COMMIT =~ HEAD.* ]] || [[ $COMMIT =~ [0-9a-f]{5,40} ]]; then
        git rebase --interactive --autosquash $COMMIT
    else
        git rebase --interactive --autosquash HEAD~$1
    fi

}

main $@
