#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Updates DEVELOPMENT_BRANCH from origin, then rebase current branch onto it."

source "$(git --exec-path)/git-sh-setup"

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES and DEVELOPMENT_BRANCH.'
    fi
}

function main() {

    current_branch=$(git rev-parse --abbrev-ref HEAD)

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only
    git checkout $current_branch
    git rebase $DEVELOPMENT_BRANCH

}

setup_configuration
main
