#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Updates DEVELOPMENT_BRANCH to the current branch."

source "$(git --exec-path)/git-sh-setup"

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'error: Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES and DEVELOPMENT_BRANCH.'
    fi
}

function main() {
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ $PROTECTED_BRANCHES =~ $current_branch ]]; then
        die "error: Current branch \"$current_branch\" is protected."
    fi

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only
    git merge --ff-only $current_branch
    git checkout $current_branch
}

setup_configuration
main
