#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Interactive rebase with autosquash to current branch's oldest ancestor from DEVELOPMENT_BRANCH."

source "$(git --exec-path)/git-sh-setup"

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES and DEVELOPMENT_BRANCH.'
    fi
}

function main() {

    oldest_ancestor=$(diff --old-line-format='' --new-line-format='' <(git rev-list --first-parent "${1:-$DEVELOPMENT_BRANCH}") <(git rev-list --first-parent "${2:-HEAD}") | head -1)
    git rebase --interactive --autosquash $oldest_ancestor

}

setup_configuration
main
