#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Updates DEVELOPMENT_BRANCH from origin, then rebase current branch onto it."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.sh"

function main() {
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ $PROTECTED_BRANCHES =~ $current_branch ]]; then
        die "error: Current branch \"$current_branch\" is protected."
    fi

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only
    git checkout $current_branch
    git rebase $DEVELOPMENT_BRANCH
}

setup_configuration
main