#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Closes current feature branch by updating DEVELOPMENT_BRANCH into it."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.bash"

function main() {
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ $PROTECTED_BRANCHES =~ $current_branch ]]; then
        die "error: Current branch \"$current_branch\" is protected."
    fi

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only
    git merge --ff-only $current_branch
    git push
    git checkout $current_branch
}

setup_configuration
main