#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Updates the current branch's base from its configured upstream, then rebases current branch onto it."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.bash"

setup_configuration

current_branch=$(git rev-parse --abbrev-ref HEAD)
base_branch=$(git_line_current_branch_base "$current_branch" || true)

if [[ $PROTECTED_BRANCHES =~ $current_branch ]]; then
    die "error: Current branch \"$current_branch\" is protected."
fi

if [[ -z $base_branch ]]; then
    base_branch=$DEVELOPMENT_BRANCH
fi

git_line_fetch_branch_from_upstream_if_available "$base_branch"
git rebase "$base_branch"
