#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Finishes current branch by squashing all commits into one on DEVELOPMENT_BRANCH."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.bash"

function main() {
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ $PROTECTED_BRANCHES =~ $current_branch ]]; then
        die "error: Current branch \"$current_branch\" is protected."
    fi

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only

    git merge --squash $current_branch

    commit_message=$(echo "$current_branch" | tr _-/ \ )
    git commit -am "$commit_message"
}

setup_configuration
main