#!/usr/bin/env bash

USAGE="<branch_name>"
LONG_USAGE="Creates a branch starting from DEVELOPMENT_BRANCH."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.bash"

setup_configuration

BRANCH_NAME=$(echo "$2" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | tr \  -)

if [[ -z $BRANCH_NAME ]] || [[ -n $3 ]]; then
    usage
    exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

timestamp=$(date +%T)
git stash push -m "git-line-start-$current_branch-$timestamp"

git checkout $DEVELOPMENT_BRANCH
git pull --ff-only

if [[ "$BRANCH_PREFIX_ENABLED" == "true" ]]; then
    BRANCH_NAME="$BRANCH_PREFIX/$BRANCH_NAME"
fi

git checkout -b "$BRANCH_NAME"
