#!/usr/bin/env bash

USAGE="<feature>"
LONG_USAGE="Creates a feature branch starting from DEVELOPMENT_BRANCH."

source "$(git --exec-path)/git-sh-setup"

function setup_configuration() {
    if [[ -r "$HOME/.git-extensions.conf" ]]; then
        source "$HOME/.git-extensions.conf"
    fi

    git_root=$(git rev-parse --show-toplevel)

    if [[ -r "$git_root/.git-extensions.conf" ]]; then
        source "$git_root/.git-extensions.conf"
    fi

    if [[ -z $PROTECTED_BRANCHES ]] || [[ -z $DEVELOPMENT_BRANCH ]]; then
        die 'error: Please create a .git-extensions.conf file in your git root directory and specify PROTECTED_BRANCHES and DEVELOPMENT_BRANCH.'
    fi
}

function main() {
    FEATURE_NAME=$2

    if [[ -z $FEATURE_NAME ]]; then
        usage
        exit 1
    fi

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only
    git checkout -b "feature/$FEATURE_NAME"
}

setup_configuration
main $@