#!/usr/bin/env bash

USAGE="<feature>"
LONG_USAGE="Creates a feature branch starting from DEVELOPMENT_BRANCH."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.bash"

function main() {
    FEATURE_NAME=$2

    if [[ -z $FEATURE_NAME ]]; then
        usage
        exit 1
    fi

    git checkout $DEVELOPMENT_BRANCH
    git pull --ff-only

    if [[ "$BRANCH_PREFIX_ENABLED" == "true" ]]; then
        FEATURE_NAME="$BRANCH_PREFIX/$FEATURE_NAME"
    fi

    git checkout -b "$FEATURE_NAME"
}

setup_configuration
main $@