#!/usr/bin/env bash

USAGE=""
LONG_USAGE="Interactive rebase with autosquash to current branch's oldest ancestor from DEVELOPMENT_BRANCH."

source "$(git --exec-path)/git-sh-setup"
source "git-line_utils.sh"

function main() {
    oldest_ancestor=$(diff --old-line-format='' --new-line-format='' <(git rev-list --first-parent "${1:-$DEVELOPMENT_BRANCH}") <(git rev-list --first-parent "${2:-HEAD}") | head -1)
    git rebase --interactive --autosquash $oldest_ancestor
}

setup_configuration
main